apiVersion: v1
kind: Service
metadata:
  name: episode5backend-service
spec:
  type: NodePort
  selector:
    app: episode5backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 4000
      nodePort: 30009
