apiVersion: v1
kind: Service
metadata:
  name: episode2backend-service
spec:
  type: NodePort
  selector:
    app: episode2backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 4000
      nodePort: 30001
