# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: episode2frontend-service
spec:
  type: NodePort
  selector:
    app: episode2frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
