apiVersion: v1
kind: Service
metadata:
  name: episode1backend-service
spec:
  type: NodePort
  selector:
    app: episode3backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 4000
      nodePort: 30004
