apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sheraztariq22/episode1frontend:latest
          ports:
            - containerPort: 30
