# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: episode1frontend-service
spec:
  type: NodePort
  selector:
    app: episode1frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30005
