apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode1frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: episode1frontend
  template:
    metadata:
      labels:
        app: episode1frontend
    spec:
      containers:
        - name: episode1frontend
          image: sheraztariq22/episode1frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi" # Request 256 megabytes of memory
            limits:
              memory: "512Mi" # Limit to 512 megabytes of memory
