apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode3backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: episode3backend
  template:
    metadata:
      labels:
        app: episode3backend
    spec:
      containers:
        - name: episode3backend
          image: sheraztariq22/episode3backend
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "256Mi" # Request 256 MB of memory
            limits:
              memory: "512Mi" # Limit to 512 MB of memory
