apiVersion: v1
kind: Service
metadata:
  name: episode5frontend-service
spec:
  type: NodePort
  selector:
    app: episode5frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008
